name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tree-sitter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: tree-sitter/setup-action/cli@v2
      - name: tree-sitter test
        run: tree-sitter test
      - name: tree-sitter generate (check up to date)
        run: |
          tree-sitter generate
          git diff --exit-code
