name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tree-sitter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: NixOS/nix-installer-action@main
        with:
          extra-conf: |
            auto-optimise-store = false
            cores = 0
            max-substitution-jobs = 32
            http-connections = 50
            download-buffer-size = 2560000
      - uses: nix-community/cache-nix-action@main
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
      - uses: nicknovitski/nix-develop@v1
      - name: tree-sitter test
        run: tree-sitter test
      - name: tree-sitter generate (check up to date)
        run: |
          tree-sitter generate
          git diff --exit-code

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: NixOS/nix-installer-action@main
      - uses: nix-community/cache-nix-action@main
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
      - name: nix fmt
        run: nix fmt -- --ci
      - name: actionlint
        run: nix develop -c actionlint
